### ISSUE TITLE
Narrative buer: Tillate søk etter flere ord

### ISSUE THREAD

**Issue by Ingerid** [NationalLibraryOfNorway/DHLAB#108]
Foreløpig kan appen "narrative buer" bare plotte enkeltord, men vi vil også kunne plotte flere ord/uttrykk.

**Comment by Ingerid** [comment]
@Yoonsen  @magbb  Vet dere hvor kodeendringen bør skje? Her eller på serversiden?

**Comment by Yoonsen** [comment]
De narrative buene bygges over api-et, så strengt tatt er det et issue for dhlab og ikke appen. For enkeltverk kan vi rimelig kjapt sette opp en slik kobling. Altså at vi går fra at egenskaper er globale (prefabrikerte for alle bøker, slik det er for enkeltord og bigram) til at de i større grad beregnes on-the-fly ala slik vi gjør med spaCy i forbindelse med POS- og NER-annotering.

**Comment by Yoonsen** [comment]
Jeg ser at i narrative buer så gjøres jo tellingen uansett på boknivå, med en form for chunking, men i motsetnng til chunking så tar buene vare på sekvensinformasjonen. Siden de går på enkelttekster først og fremst, kunne vi tenkt oss muligheten til å se på lemmatiserte utgaver av tekstene. I første omgang kan vi sette på et parameter for n-gram.

**Comment by Ingerid** [comment]
Denne funksjonen er på plass.
