### ISSUE TITLE
Integrere jupyter notebooks i dokumentasjonssidene 

### ISSUE THREAD

**Issue by Ingerid** [NationalLibraryOfNorway/DHLAB#11]

**Comment by Yoonsen** [comment]
En del dokumentasjon kan kanskje bygges opp som en notebook? At vi tar ut kode og kommentarer og formaterer dem slik at de kan limes rett inn? Er dokumentasjonssidene markdown eller markup (eller begge?)

**Comment by Ingerid** [comment]
> En del dokumentasjon kan kanskje bygges opp som en notebook? 

Ja, jeg synes det er en god idé å fortsette med eksempelkode i notebooks som demonstrerer hvordan funksjonene skal brukes. Vi kan gå gjennom de som finnes i repoet https://github.com/NationalLibraryOfNorway/digital_tekstanalyse og oppdatere etterhvert som funksjonskallene endrer seg og flere kommer til. 

>  Er dokumentasjonssidene markdown eller markup (eller begge?)

Jeg har lastet inn en extension som tillater markdown (`.md`-filer), men ellers brukes reStructuredText i docstringene under funksjons- og metodesignaturene. Det er disse som brukes til å generere dokumentasjonen på nettsiden automatisk.

**Comment by Ingerid** [comment]
Jupyter Notebooks fra digital_tekstanalyse-repoet er inkludert i dokumentasjonssidene som statiske, skrollbare nettsider, f.eks: 
https://dhlab.readthedocs.io/en/update_docs/notebooks/Oppstart.html
