### ISSUE TITLE
dh.Corpus() - frys seeden på random

### ISSUE THREAD

**Issue by mich123prem** [NationalLibraryOfNorway/DHLAB#151]
Hadde det gått an å fryse seeden på random-kriteriet?
Michael

**Comment by Yoonsen** [comment]
Det er litt tricky, i og med at selve random-funksjonen ligger i SQLite på serversden. Om du har en idé til hvordan den kan finnes, kan vi se på det.

Hilsen
Lars

**Comment by mich123prem** [comment]
Ser at sqlite ikke støtter order by random(seed), så det blir vanskelig.

Sendt fra Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Yoonsen** [comment]
Da lukker jeg saken. Men vi skal være obs på problemstillingen.
