### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by trym-b** [NationalLibraryOfNorway/DHLAB#163]
Hi

I discovered this repository and could not avoid noticing that it is unlicensed. According to [Github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license) this is what they say about no license:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The [Open Source Guide](https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project) provides additional guidance on choosing the correct license for your project.

It may put off external people from even using this code if it remains unlicensed.

**Comment by tungland** [comment]
Thanks. Fixed

**Comment by tungland** [comment]
This code is distributed under the MIT license. License file was missing from main repo.
