### ISSUE TITLE
Oppdater konfigurasjon og rammeverk for pakken

### ISSUE THREAD

**Issue by Ingerid** [NationalLibraryOfNorway/DHLAB#166]
Setuptools legger opp til at man bruker `pyproject.toml` for å konfigurere metadata for dhlab-python-pakken + alle innstillinger for tredjepartsverktøy og dependencies: https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html.

Fordeler: 
- Versjonsoppdatering: Å ha én konfigurasjonsfil i pyproject.toml gjør det lettere å håndtere versjonsoppdatering ~~(f.eks. med [`setuptools_scm`](https://github.com/pypa/setuptools_scm/) fremfor [`commitizen`](https://commitizen-tools.github.io/commitizen/) (som brukes i [`bump-version.yml`](https://github.com/NationalLibraryOfNorway/DHLAB/blob/main/.github/workflows/bump-version.yml)). Setuptools_scm oppdaterer også versjon basert på git-endringer, men er ikke like streng på commit-meldingene som commitizen.~~
- Dependencies: Verktøy som [poetry](https://python-poetry.org/)~~, pip-tools, [pipenv](https://pip.pypa.io/en/stable/), [hatch](https://hatch.pypa.io/latest/) osv.~~ kan hjelpe oss med å oppdatere/oppgradere requirements-fila og håndtere versjonene på tredjepartspakker + bygge pakken for oss. 
~~- Testing + linting: hovedkonfigurasjonen kan defineres i pyproject, slik at testene kjøres som forventet når man ikke spesifiserer parametere fra kommandolinjen. Deretter kan vi bruke andre verktøy (pre-commit, github actions, git hooks osv.) for å kjøre dem automatisk ved ønsket trigger event (f.eks. før man kjører commit eller push eller åpner PR).~~ 

- [x] Flytt konfigurasjonen fra setup.cfg til pyproject.toml
- [x] #167

(endringer 2023-08-23: strøk over alternativer vi ikke går for, og la til oppgave for å bruke poetry)

**Comment by tungland** [comment]
Da erstatter den den nåværende løypa for versjonoppdatering?

**Comment by Ingerid** [comment]
> Da erstatter den den nåværende løypa for versjonoppdatering?

Ja. Setuptools_scm bruker git-historikken til å sette versjonen, og inkrementerer med pre-release og dev-hash dersom det ikke er en major/minor/patch-oppdatering, om jeg har forstått det riktig. Skal sette opp en prototyp for det på en ny gren.

**Comment by Ingerid** [comment]
## Status 2023-08-08: 

PR #170 introduserer en produksjonsløype for dhlab-pakken med poetry: 
- test koden med pytest (trigges av PR til `main`)
- lint + reformater koden med black (trigges av PR til `main`)
- publiser en ny release med poetry (trigges av at en versjonstag "*.*.*" blir pushet). 
  - ~~[versjonen blir oppdatert](https://github.com/mtkennerly/poetry-dynamic-versioning) basert på git historikken~~ (konfigureres i pyporject.toml, foreløpig slått av)
  - python-pakken blir bygget
  - Pakken publiseres i en github release
  - Kommandoene for å publisere pakken på pypi og testpypi blir printet til github actions-loggen. 

TODO før de nye innstillingene merges til `main`: 
- [ ] Publiser nye pakker til pypi
