### ISSUE TITLE
BUG: Missing beautifulsoup dependency

### ISSUE THREAD

**Issue by MarieRoald** [NationalLibraryOfNorway/DHLAB#181]
Beautifulsoup is used as a dependency in `dhlab.legacy.nb_external_files` and `dhlab.legacy.nbtext`, which is automatically imported in the root `__init__.py` file. However, it's not listed as a dependency in the `pyproject.toml`-file, so any import to dhlab will crash in an empty environment.

## Steps to reproduce
```bash
python -m .venv venv
source .venv/bin/activate  # or .venv/Scripts/activate on windows
pip install dhlab
python -c "import dhlab"
```
```raw
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\marie\dette_er_en_test\.venv\Lib\site-packages\dhlab\__init__.py", line 3, in <module>
    from dhlab.legacy import (
  File "C:\Users\marie\dette_er_en_test\.venv\Lib\site-packages\dhlab\legacy\nbtext.py", line 19, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

## Possible fixes
I see a couple of possible fixes, and I'm happy to submit a pull request based on your preference🙂.

### 1. Add BeautifulSoup as a dependency
Add the following line to the `pyproject.toml`-file
```toml
beautifulsoup4 = "*"
```

### 2. Add BeautifulSoup as an optional dependency and use lazy imports BeautifulSoup
Add the following lines to the `pyproject.toml`-file
```toml
[tool.poetry.group.legacy]
optional = true

[tool.poetry.group.legacy.dependencies]
beautifulsoup4 = "*"
```

And move the BeautifulSoup import in `dhlab/legacy/nbtext.py` and `dhlab/legacy/nb_external_files.py`

`dhlab/legacy/nb_external_files.py`:
```python
from warnings import warn

[...]

def get_urns_from_docx(document) -> List:
    """Find all URNs specified in a Word document,
    typically a ``.docx`` file."""
    
    try:
        from bs4 import BeautifulSoup
    except ImportError:
        raise ImportError("beautifulsoup4 is needed for `get_urns_from_docx`")

    with zipfile.ZipFile(document, 'r') as zfp:
        with zfp.open('word/document.xml') as fp:
            soup = BeautifulSoup(fp.read(), 'xml')

    return re.findall("[0-9]{13}", str(soup))
```

`dhlab/legacy/nbtext.py`:
```python
from warnings import warn

[...]

def text_from_html_file(filename):
    """Get a flat list of tokens from a file"""
    try:
        from bs4 import BeautifulSoup
    except ImportError:
        raise ImportError("beautifulsoup4 is needed for `text_from_html_file`")

    with open(filename, encoding='utf-8') as f:
        content = f.read()
    soup = BeautifulSoup(content, 'html.parser')
    text = []
    for para in soup.find_all('p'):
        text += tokenize(para.text)
    return text
```

### 3. Add BeautifulSoup as an optional dependency and remove the `from dhlab.legacy import (...)` statement in `__init__.py`
Add the following lines to the `pyproject.toml`-file
```toml
[tool.poetry.group.legacy]
optional = true

[tool.poetry.group.legacy.dependencies]
beautifulsoup4 = "*"
```

And remove the following lines from `dhlab/__init__.py`
```python
from dhlab.legacy import (
    graph_networkx_louvain,
    module_update,
    nb_external_files,
    nbpictures,
    nbtext,
    token_map,
)
```

**Comment by tungland** [comment]
Thanks for pointing this out! We recently switched to poetry. Seems to be some teething problems. Should be fixed now with 2.28.2

**Comment by tungland** [comment]
And thanks for the detailed post! Very helpful! Are you using dhlab for something in particular?

**Comment by MarieRoald** [comment]
I made this little streamlit app to explore the collections in a fun way: https://github.com/MarieRoald/bookshelfpoetry
