### ISSUE TITLE
publisering

### ISSUE THREAD

**Issue by Yoonsen** [NationalLibraryOfNorway/DHLAB#23]
Hvordan foregår publiseringssystemet? Altså gangen fra github til pypi?

**Comment by Ingerid** [comment]
`upload-package.yml`-filen i `.github/workflows`-mappa  styrer pypi-publiseringen av pakker for oss. 

Den bygger python-pakken `dhlab` med `build` (https://pypi.org/project/build/), og  laster den opp til pypi (via personal-access-token til pypi som er lenket til dette repoet, det er min token som er lagt til i settings). 

Foreløpig er denne prosessen  konfigurert til å kjøre når en release publiseres på github: 
https://github.com/NationalLibraryOfNorway/DHLAB/blob/main/.github/workflows/upload-package.yml#L5
