### ISSUE TITLE
Fiks API-kallene i DHLAB v1.0.0 

### ISSUE THREAD

**Issue by Ingerid** [NationalLibraryOfNorway/DHLAB#24]
dhlab v1.0.0 har en del API-kall som går til en maskin som har krasjet, og notebookene som benytter seg av API-wrapper-funksjonene fungerer ikke som forventet lenger. 

**Funksjonalitetskrav:**
* Alle notebookene i https://github.com/NationalLibraryOfNorway/digital_tekstanalyse  kan kjøres gjennom uten feilmeldinger. 
* API-kallene fra DHLAB v1 går til en maskin som kjører, og henter ut forventet informasjon. 
* API-kallene som henter informasjon som ikke er tilgjengelig lenger, printer en beskjed om dette og foreslår et alternativ.

**Comment by Yoonsen** [comment]
Det ser ut som maskinen vil være oppe å gå igjen neste uke. Kallene kan vi uansett jobbe med, men det gir oss litt tid.

**Comment by Ingerid** [comment]
> Mulig at en dekorator eller noe kan hjelpe oss med det. Altså at vi reruter alle kall til requests.get/post til kall som går mot de nye databasene. Mulig vi kan flytte alt til ny disk og ta det derfra.

God idé.
