### ISSUE TITLE
Flake8 linting

### ISSUE THREAD

**Issue by Yoonsen** [NationalLibraryOfNorway/DHLAB#32]
Justering av Flake8 

 1. Gir E(rror) på feil med import. Can't import module, når modulene kan importeres
 2. Foreslår at feil på trailing blanks tas bort, om det ikke er viktig.
 3. Midlertidig ta bort advarsel (W) for kodeduplisering - ta det inn igjen når vi er rimelig sikre på at det ikke skal være noen.

Ad pkt 3 - er det duplisering pga kode som gjenbrukes fra dhlab1. Det kan vi kanskje ordne med litt import-gymnastikk. Vet ikke hvor mye det trekker ned, men tipper at E på import trekker en del ned, sånn at koden vaker rundt grenseverdien 8 hele tiden.

**Comment by Ingerid** [comment]
Status 2023-08-09: 

PR #170 introduserer [black](https://black.readthedocs.io/en/stable/) til linting + automatisk reformatering i henhold til pep8 i github workflows. 

Dermed blir dette issuet om flake8 redundant.
