### ISSUE TITLE
defaultverdier som ["hallo"]

### ISSUE THREAD

**Issue by Yoonsen** [NationalLibraryOfNorway/DHLAB#33]
Det er anbefalt å ikke skrive funksjoner som den under, og flake-testen klager også på det

```
def f(a = [1,2]):
    ....
```
og at man i stedet gjør som her
```
df f(a =  None):
    if a is None:
        a = [1,2]
```

Det siste er jo betydelig mer kronglete, og gjemmer unna semantikken til funksjonen. Det er jo heller ingen fare med første versjon slik den er brukt i dhlab for parametre som kun leses (i gamle dager var det en distinksjon mellom call by value og call by reference - C og Pascal hadde de tingene). 

Vi kunne prøve å ta det med i dokumentasjonen av funksjonen, og/eller finne en måte å fortelle Flake8 at variabelen kun skal leses og ikke oppdateres. Jeg har ikke sett at det her skal skape problemer for rene lese-variabler.

Så, er det mulig å få slått av advarselen i Flake8 for lesevariable? Eller har Python en måte å gjøre det på?

**Comment by Ingerid** [comment]
Forslag 1: I tilfellene vi har en liste med default-verdier som vi ønsker å bruke i en funksjon, men ikke skrive til, kan vi definere det som en tuple direkte i parameterne. 

Forslag 2: Vi bruker type hint i funksjonssignaturen.

**Comment by Yoonsen** [comment]
Høres bra ut med type-hint.

Når det gjelder omskriving av defaultverdier (lister til tupler), vil det kunne skape andre problemer.

Det vi kan gjøre i første omgang, og som er bredt implementert i den koden jeg selv har skrevet i det siste, er å bare la det meste av argumenter stå med None som default. Når det gjelder lister som argument (og andre muterbare) så kan de sikkert bare stå som None og ikke initialiseres med noen eksplisitt verdi. Om noe skal endres må det uansett gis eksplisitt. Det er flere veier utenom standard omskriving.
