### ISSUE TITLE
Dewey i korpusbyggeren

### ISSUE THREAD

**Issue by tungland** [NationalLibraryOfNorway/DHLAB#81]
Jeg får ikke korpusobjektet til å virke med søk på eksakt Dewey-kode. Men det funker i når man søker direkte i API.

``` {"ddk": "\"839.82\""}```
Denne virker i Swagger

```dh.Corpus(doctype='digibok',` from_year=1960, to_year=1970, ddk="\"839.82\"", limit=10000)```

Denne koden gir følgende feil: ```JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

```dh.Corpus(doctype='digibok', from_year=1960, to_year=1970, ddk="839.82", limit=10000)```
Denne koden eksekverer, men får ingen treff

**Comment by magbb** [comment]
Løst med #82
